A few new IMABI links and minor clean-up
Jisho-org/jisho-notes pull request #5
Opened 2024-10-28 00:03 UTC by salixh5

* Removed Id 6 from being searchable, as the link seems to be eternally dead
* Changed IMABI to all upper-case to mirror the spelling they use themselves nowadays
* Adds a few new links to IMABI pages to already existing entries

Hopefully I got the syntax wrong. Seems like I must've deleted the little helper tool that I made like... 10 years ago ☺️ Not sure if you plan to use this file with the subsequent version of Jisho.org and if it still it relevant, but somehow tonight I felt the urge to give it a minor update.

2024-10-30 06:36 UTC, Kimtaro requested changes
This is great, thank you! I just applied these changes to Jisho.

Before I merge this, can you reinstate the last `---`?

2024-10-30 06:36 UTC, Kimtaro commented on jisho-notes.md
> -
Can you reinstate this section? The `---` is needed for the parser to read the last entry.

2024-10-30 06:38 UTC, Kimtaro commented
I don't know how well used this feature is in current Jisho, but I'd like to expand it for the next version as I think it can be quite useful. I haven't decided on the exact shape this will take, but it'll be based on this file, or I might make a web admin interface.

2024-10-30 10:08 UTC, salixh5 commented on jisho-notes.md
> -
Ok should be fixed.

2024-10-31 02:28 UTC, Kimtaro approved these changes

2024-10-31 02:28 UTC, Kimtaro commented
Thank you!

2024-10-31 02:28 UTC, merged